FROM golang:1.25-alpine AS builder
WORKDIR /src
RUN apk add --no-cache build-base pkgconf git ca-certificates vips-dev

COPY go.mod go.sum ./
RUN go mod download
COPY . .

ENV CGO_ENABLED=1
RUN go build -o /app/imagine ./cmd/api

FROM alpine:3.19 AS runtime
WORKDIR /app
RUN apk add --no-cache vips ca-certificates

COPY --from=builder /app/imagine /app/imagine
COPY imagine.json /app/imagine.json

EXPOSE 7770
ENV ENV=production
CMD ["/app/imagine"]