package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// EntityConfig defines which OpenAPI types should become GORM entities
type EntityConfig struct {
	Name          string   // DTO type name from OpenAPI
	TableName     string   // Optional custom table name
	PKField       string   // Primary key field (default: "ID")
	SoftDelete    bool     // Add DeletedAt
	Indexes       []string // Fields to index
	UniqueIndexes []string // Fields with unique indexes
	Fields        []FieldConfig
}

type FieldConfig struct {
	Name     string
	TypeExpr string // Rendered Go type for entity field
	IsSimple bool   // If false, add gorm serializer:json
}

const tmpl = `// Code generated by genentities. DO NOT EDIT.
package entities

import (
	"gorm.io/gorm"
	"imagine/internal/dto"
	"time"
)

{{range .Entities}}
// {{.Name}} is a GORM entity inferred from dto.{{.Name}}
type {{.Name}} struct {
	{{if .PKField}}{{.PKField}} uint ` + "`gorm:\"primarykey\" json:\"-\"`" + `{{end}}
	{{if .SoftDelete}}DeletedAt gorm.DeletedAt ` + "`gorm:\"index\" json:\"-\"`" + `{{end}}
	CreatedAt time.Time
	UpdatedAt time.Time
	{{- range .Fields}}
	{{.Name}} {{.TypeExpr}} {{if not .IsSimple}}` + "`gorm:\"serializer:json;type:JSONB\"`" + `{{end}}
	{{- end}}
}

func (e {{.Name}}) DTO() dto.{{.Name}} {
	return dto.{{.Name}}{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		{{- range .Fields}}
		{{.Name}}: e.{{.Name}},
		{{- end}}
	}
}

{{end}}
`

type templateData struct {
	Entities []EntityConfig
}

func main() {
	dtoFile := flag.String("dto", "internal/dto/types.gen.go", "Path to generated DTO file")
	outFile := flag.String("o", "internal/entities/generated.go", "Output file path")
	flag.Parse()

	// Discover entities
	discovered, err := discoverEntities(*dtoFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to discover entities: %v\n", err)
		os.Exit(1)
	}

	// Infer fields for each entity
	entities, err := populateEntityFields(*dtoFile, discovered)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to analyze DTO fields: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Auto-discovered %d entities: ", len(entities))
	for i, e := range entities {
		if i > 0 {
			fmt.Print(", ")
		}
		fmt.Print(e.Name)
	}
	fmt.Println()

	t := template.Must(template.New("entities").Parse(tmpl))

	var buf bytes.Buffer
	if err := t.Execute(&buf, templateData{Entities: entities}); err != nil {
		fmt.Fprintf(os.Stderr, "Template execution failed: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to format generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(*outFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated GORM entities in %s\n", *outFile)
}

// discoverEntities parses the DTO file and finds types that look like entities.
// Heuristic: structs with `uid`, `created_at`, and `updated_at` fields are treated as entities.
func discoverEntities(dtoPath string) ([]EntityConfig, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, dtoPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse DTO file: %w", err)
	}

	var entities []EntityConfig

	ast.Inspect(node, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		// Analyze struct fields to see if it matches entity pattern
		hasUID := false
		hasCreatedAt := false
		hasUpdatedAt := false
		var uniqueIndexes []string

		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			fieldName := field.Names[0].Name
			lowerName := strings.ToLower(fieldName)

			if lowerName == "uid" {
				hasUID = true
				uniqueIndexes = append(uniqueIndexes, fieldName)
			}
			if lowerName == "createdat" {
				hasCreatedAt = true
			}
			if lowerName == "updatedat" {
				hasUpdatedAt = true
			}
		}

		// If it has the entity signature (uid + created_at + updated_at), add it
		if hasUID && hasCreatedAt && hasUpdatedAt {
			entities = append(entities, EntityConfig{
				Name:          typeSpec.Name.Name,
				SoftDelete:    true,
				UniqueIndexes: uniqueIndexes,
				PKField:       "ID",
			})
		}

		return true
	})

	return entities, nil
}

// populateEntityFields inspects the DTO structs for each entity and infers field types and JSON storage.
func populateEntityFields(dtoPath string, entities []EntityConfig) ([]EntityConfig, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, dtoPath, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse DTO file: %w", err)
	}

	// Build map of name -> *ast.StructType
	structMap := map[string]*ast.StructType{}
	ast.Inspect(node, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}
		structMap[ts.Name.Name] = st
		return true
	})

	isBasic := func(name string) bool {
		switch name {
		case "string", "bool", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return true
		default:
			return false
		}
	}

	var renderType func(expr ast.Expr) (string, bool)
	renderType = func(expr ast.Expr) (typeStr string, simple bool) {
		switch t := expr.(type) {
		case *ast.Ident:
			if isBasic(t.Name) {
				return t.Name, true
			}
			if t.Name == "Time" {
				return "time.Time", true
			}
			return "dto." + t.Name, false
		case *ast.StarExpr:
			inner, s := renderType(t.X)
			// pointer to dto or composite becomes non-simple
			if strings.HasPrefix(inner, "dto.") || strings.HasPrefix(inner, "[]") || strings.HasPrefix(inner, "map[") {
				return "*" + inner, false
			}
			return "*" + inner, s
		case *ast.ArrayType:
			elt, _ := renderType(t.Elt)
			return "[]" + elt, false
		case *ast.SelectorExpr:
			if x, ok := t.X.(*ast.Ident); ok && x.Name == "time" && t.Sel.Name == "Time" {
				return "time.Time", true
			}
			return "dto." + t.Sel.Name, false
		case *ast.MapType:
			key, _ := renderType(t.Key)
			val, _ := renderType(t.Value)
			return "map[" + key + "]" + val, false
		default:
			return "any", false
		}
	}

	// Build entities with fields
	for i, e := range entities {
		st := structMap[e.Name]
		if st == nil {
			continue
		}
		var fields []FieldConfig
		for _, f := range st.Fields.List {
			if len(f.Names) == 0 {
				continue
			}
			name := f.Names[0].Name
			lowerName := strings.ToLower(name)

			// Skip GORM-managed timestamp fields - GORM will handle these automatically
			if lowerName == "createdat" || lowerName == "updatedat" {
				continue
			}

			tStr, simple := renderType(f.Type)
			if strings.HasPrefix(tStr, "dto.") || strings.HasPrefix(tStr, "[]") || strings.HasPrefix(tStr, "map[") {
				simple = false
			}
			fields = append(fields, FieldConfig{Name: name, TypeExpr: tStr, IsSimple: simple})
		}
		entities[i].Fields = fields
	}

	return entities, nil
}
