// Code generated by genentities. DO NOT EDIT.
package entities

import (
	"gorm.io/gorm"
	"imagine/internal/dto"
	"time"
)

// Collection is a GORM entity inferred from dto.Collection
type Collection struct {
	ID          uint           `gorm:"primarykey" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	CreatedBy   *User `gorm:"foreignKey:CreatedByID;references:Uid"`
	Description *string
	ImageCount  int
	Images      *[]dto.CollectionImage `gorm:"serializer:json;type:JSONB"`
	Name        string
	Private     *bool
	ThumbnailID *string
	Thumbnail   *Image `gorm:"foreignKey:ThumbnailID;references:Uid"`
	Uid         string `gorm:"uniqueIndex"`
}

func (e Collection) DTO() dto.Collection {
	return dto.Collection{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		CreatedBy: func() *dto.User {
			if e.CreatedBy != nil {
				d := e.CreatedBy.DTO()
				return &d
			}
			return nil
		}(),
		Description: e.Description,
		ImageCount:  e.ImageCount,
		Images:      e.Images,
		Name:        e.Name,
		Private:     e.Private,
		Thumbnail: func() *dto.Image {
			if e.Thumbnail != nil {
				d := e.Thumbnail.DTO()
				return &d
			}
			return nil
		}(),
		Uid: e.Uid,
	}
}

// CollectionDetailResponse is a GORM entity inferred from dto.CollectionDetailResponse
type CollectionDetailResponse struct {
	ID          uint           `gorm:"primarykey" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	CreatedBy   *User `gorm:"foreignKey:CreatedByID;references:Uid"`
	Description *string
	ImageCount  *int
	Images      dto.ImagesPage `gorm:"serializer:json;type:JSONB"`
	Name        string
	Private     *bool
	ThumbnailID *string
	Thumbnail   *Image `gorm:"foreignKey:ThumbnailID;references:Uid"`
	Uid         string `gorm:"uniqueIndex"`
}

func (e CollectionDetailResponse) DTO() dto.CollectionDetailResponse {
	return dto.CollectionDetailResponse{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		CreatedBy: func() *dto.User {
			if e.CreatedBy != nil {
				d := e.CreatedBy.DTO()
				return &d
			}
			return nil
		}(),
		Description: e.Description,
		ImageCount:  e.ImageCount,
		Images:      e.Images,
		Name:        e.Name,
		Private:     e.Private,
		Thumbnail: func() *dto.Image {
			if e.Thumbnail != nil {
				d := e.Thumbnail.DTO()
				return &d
			}
			return nil
		}(),
		Uid: e.Uid,
	}
}

// Image is a GORM entity inferred from dto.Image
type Image struct {
	ID            uint           `gorm:"primarykey" json:"-"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   *string
	Exif          *dto.ImageEXIF `gorm:"serializer:json;type:JSONB"`
	Height        int32
	ImageMetadata *dto.ImageMetadata `gorm:"serializer:json;type:JSONB"`
	ImagePaths    dto.ImagePaths     `gorm:"serializer:json;type:JSONB"`
	Name          string
	Private       bool
	Processed     bool
	Uid           string `gorm:"uniqueIndex"`
	UploadedByID  *string
	UploadedBy    *User `gorm:"foreignKey:UploadedByID;references:Uid"`
	Width         int32
}

func (e Image) DTO() dto.Image {
	return dto.Image{
		CreatedAt:     e.CreatedAt,
		UpdatedAt:     e.UpdatedAt,
		Description:   e.Description,
		Exif:          e.Exif,
		Height:        e.Height,
		ImageMetadata: e.ImageMetadata,
		ImagePaths:    e.ImagePaths,
		Name:          e.Name,
		Private:       e.Private,
		Processed:     e.Processed,
		Uid:           e.Uid,
		UploadedBy: func() *dto.User {
			if e.UploadedBy != nil {
				d := e.UploadedBy.DTO()
				return &d
			}
			return nil
		}(),
		Width: e.Width,
	}
}

// User is a GORM entity inferred from dto.User
type User struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	FirstName string
	LastName  string
	Role      dto.UserRole `gorm:"serializer:json;type:JSONB"`
	Uid       string       `gorm:"uniqueIndex"`
	Username  string
}

func (e User) DTO() dto.User {
	return dto.User{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		Email:     e.Email,
		FirstName: e.FirstName,
		LastName:  e.LastName,
		Role:      e.Role,
		Uid:       e.Uid,
		Username:  e.Username,
	}
}
