// Code generated by genentities. DO NOT EDIT.
package entities

import (
	"gorm.io/gorm"
	"imagine/internal/dto"
	"time"
)

// Collection is a GORM entity inferred from dto.Collection
type Collection struct {
	ID          uint           `gorm:"primarykey" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedBy   *string
	Description *string
	ImageCount  int
	Images      *[]dto.CollectionImage `gorm:"serializer:json;type:JSONB"`
	Name        string
	Private     *bool
	Uid         string
}

func (e Collection) DTO() dto.Collection {
	return dto.Collection{
		CreatedAt:   e.CreatedAt,
		UpdatedAt:   e.UpdatedAt,
		CreatedBy:   e.CreatedBy,
		Description: e.Description,
		ImageCount:  e.ImageCount,
		Images:      e.Images,
		Name:        e.Name,
		Private:     e.Private,
		Uid:         e.Uid,
	}
}

// Image is a GORM entity inferred from dto.Image
type Image struct {
	ID            uint           `gorm:"primarykey" json:"-"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   *string
	Exif          *dto.ImageEXIF `gorm:"serializer:json;type:JSONB"`
	Height        int32
	ImageMetadata *dto.ImageMetadata `gorm:"serializer:json;type:JSONB"`
	ImagePaths    *dto.ImagePaths    `gorm:"serializer:json;type:JSONB"`
	Name          string
	Private       bool
	Processed     bool
	Uid           string
	UploadedBy    *string
	Width         int32
}

func (e Image) DTO() dto.Image {
	return dto.Image{
		CreatedAt:     e.CreatedAt,
		UpdatedAt:     e.UpdatedAt,
		Description:   e.Description,
		Exif:          e.Exif,
		Height:        e.Height,
		ImageMetadata: e.ImageMetadata,
		ImagePaths:    e.ImagePaths,
		Name:          e.Name,
		Private:       e.Private,
		Processed:     e.Processed,
		Uid:           e.Uid,
		UploadedBy:    e.UploadedBy,
		Width:         e.Width,
	}
}

// User is a GORM entity inferred from dto.User
type User struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	FirstName string
	LastName  string
	Role      dto.UserRole `gorm:"serializer:json;type:JSONB"`
	Uid       string
	Username  string
}

func (e User) DTO() dto.User {
	return dto.User{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		Email:     e.Email,
		FirstName: e.FirstName,
		LastName:  e.LastName,
		Role:      e.Role,
		Uid:       e.Uid,
		Username:  e.Username,
	}
}
